---
- name: Install DevOps tools
  hosts: localhost
  gather_facts: true
  become: true
  become_user: root

  vars:
    install_awscli: true
    install_helm: true
    install_eksctl: true
    install_kubectl: true
    install_docker: true
    install_jenkins: true
    install_microk8s: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    # ---------------- AWS CLI ----------------
    - name: Install unzip
      apt:
        name: unzip
        state: present
      when: install_awscli

    - name: Download AWS CLI
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
      when: install_awscli

    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes
      when: install_awscli

    # ---------------- AWS CLI ----------------
    - name: Check if AWS CLI is already installed
      command: aws --version
      register: awscli_check
      ignore_errors: yes
      changed_when: false
      when: install_awscli

    - name: Install or update AWS CLI
      command: ./aws/install --update
      args:
        chdir: /tmp
      when: install_awscli and awscli_check.rc != 0

    # ---------------- Helm ----------------
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'
      when: install_helm

    - name: Install Helm
      command: ./get_helm.sh
      args:
        chdir: /tmp
      when: install_helm

    # ---------------- eksctl ----------------
    - name: Download eksctl
      get_url:
        url: https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_{{ ansible_system }}_amd64.tar.gz
        dest: /tmp/eksctl.tar.gz
      when: install_eksctl

    - name: Extract eksctl
      unarchive:
        src: /tmp/eksctl.tar.gz
        dest: /tmp
        remote_src: yes
      when: install_eksctl

    - name: Move eksctl to /usr/local/bin
      command: mv /tmp/eksctl /usr/local/bin/
      when: install_eksctl

    # ---------------- kubectl ----------------
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: install_kubectl

    # ---------------- Docker ----------------
    - name: Install Docker prerequisites
      apt:
        name: [ca-certificates, curl]
        state: present
      when: install_docker

    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
      when: install_docker

    - name: Install Docker (Ubuntu package)
      apt:
        name: docker.io
        state: present
      when: install_docker

    - name: Add users to docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop:
        - ubuntu
        - jenkins
      when: install_docker and install_jenkins

     # ---------------- MicroK8s ----------------
    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        state: present
      when: install_microk8s

    - name: Add current user to microk8s group
      user:
        name: "{{ ansible_env.USER }}"
        groups: microk8s
        append: yes
      when: install_microk8s

    - name: Fix kube ownership
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        owner: "{{ ansible_env.USER }}"
        recurse: yes
      when: install_microk8s

    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready
      when: install_microk8s

    - name: Add kubectl alias
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "alias kubectl='microk8s kubectl'"
        create: yes
      when: install_microk8s
